### ISSUE TITLE
Download continues ever after pressing "Cancel Current operations".

### ISSUE THREAD

**Issue by kaiser62** [ZedPea/r34-downloader#3]
I am on windows 10 64bit system and using the version v0.0.8. If I start downloading a tag, it doesn't stop until the application is closed.

**Comment by ZedPea** [comment]
@kaiser62 Yep, I can reproduce this, must have made a silly mistake. Will fix shortly.

**Comment by ZedPea** [comment]
da1a6e36846e6a9e17a6c8296e8a34aaf9c11708 fixes the issue, a new windows installer will be uploaded shortly. Thanks for the report.

**Comment by ZedPea** [comment]
https://github.com/ZedPea/r34-downloader/releases/tag/v0.0.9 Has been uploaded, let me know if it doesn't work for some reason.
